server:
  port : 7788

spring:
#  数据库默认配置
  datasource:
    url : jdbc:mysql://localhost:3306/tom-java?autoconnection&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username : root
    password : 123
    driver-class-name : com.mysql.jdbc.Driver
    type : com.alibaba.druid.pool.DruidDataSource

  application:
    name : tom-web-api

  #redis配置
  redis:
    database : 5
    host : 192.168.1.37
    port : 6379
    password : tongtongmallredis
    timeout : 1000
    expiration : 600

mybatis-plus:
  mapper-locations : classpath*:com/tom/dao/**/*.xml
  typeAliasesPackage : com.tom.model
  global-config :
    id-type : 2
    field-strategy : 2
    db-column-underline : true
    refresh-mapper : true
    logic-delete-value : 0
  configuration :
    map-underscore-to-camel-case : true
    cache-enabled : false


